--- #YAML:1.0
name:                   WWW-Scraper-ISBN-Wheelers_Driver
version:                0.09
abstract:               Search drivers for Wheelers online book catalog.
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                         5.006
  WWW::Mechanize:               1.60
  WWW::Scraper::ISBN:           0.25
  WWW::Scraper::ISBN::Driver:   0.18
recommends:
  Test::CPAN::Meta:             0
  Test::CPAN::Meta::JSON:       0
  Test::Pod:                    1.00
  Test::Pod::Coverage:          0.08
build_requires:
  IO::File:                     0
  Test::More:                   0.70

provides:
  WWW::Scraper::ISBN::Wheelers_Driver:
    file:     lib/WWW/Scraper/ISBN/Wheelers_Driver.pm
    version:  0.09
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
